name: Build Environment

on: [push, pull_request]

env:
  PIPENV_ACTIVE: 1

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwxgtk3.0-gtk3-dev libreadline-dev -y
    
    - name: '🚧 Build package'
      run: |
        make -j
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: linux
        path: bin

  macos:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew update
        brew install wxmac

    - name: '🚧 Build package'
      run: |
        make -j

    - name: '📤 Upload artifact: package'
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: macos
        path: bin
        