name: Build Environment

on: [push, pull_request]

env:
  PIPENV_ACTIVE: 1

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwxgtk3.0-gtk3-dev libreadline-dev -y
    
    - name: '🚧 Build package'
      run: |
        make -j
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: linux
        path: bin

  macos:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew update
        brew install wxmac

    - name: '🚧 Build package'
      run: |
        make -j

    - name: '📤 Upload artifact: package'
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: macos
        path: bin

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >
          git
          base-devel
          tree
          mingw-w64-x86_64-toolchain

    - name: '🚧 Build package'
      run: makepkg-mingw --noconfirm --noprogressbar -sCLf

    - run: pacman --noconfirm -U mingw-w64-*-any.pkg.tar.xz
    - run: |
        set MSYSTEM=MINGW64
        msys2do make -j

    - name: '📤 Upload artifact: package'
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: windows
        path: bin
